### ISSUE TITLE
Image missing.

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/citrix-netscaler-vpx#10]
Hello,
Images on the following URL seems missing. Could you check it?

https://console.bluemix.net/docs/infrastructure/citrix-netscaler-vpx/hsm-guide.html
https://console.bluemix.net/docs/infrastructure/citrix-netscaler-vpx/hsm-order-hsm.html
https://console.bluemix.net/docs/infrastructure/citrix-netscaler-vpx/hsm-install-hsm.html
https://console.bluemix.net/docs/infrastructure/citrix-netscaler-vpx/hsm-order-certificate.html
https://console.bluemix.net/docs/infrastructure/citrix-netscaler-vpx/hsm-retrieve-certificate.html

Thanks!

**Comment by jbmitch** [comment]
They should be fixed now, give it an hour or so to replicate. Thanks for finding.
