### ISSUE TITLE
Netscaler links not working

### ISSUE THREAD

**Issue by markpokane** [ibm-cloud-docs/citrix-netscaler-vpx#14]
Doc Page: https://cloud.ibm.com/docs/citrix-netscaler-vpx?topic=citrix-netscaler-vpx-upgrading-your-citrix-netscaler-vpx
Links not working
![Capture](https://user-images.githubusercontent.com/33838544/110358401-46d5bf00-8034-11eb-9026-f46558b6f7a0.JPG)

**Error:**
`The connection has timed out.  The server at downloads .service.softlayer.com is taking too long to respond.
`
This was with and without the VPN set up

**Comment by austinmama** [comment]
@jbmitch

**Comment by jbmitch** [comment]
Confirmed this works with correct firewall.
