### ISSUE TITLE
Clear up ambiguity on GSLB

### ISSUE THREAD

**Issue by rbraddes** [ibm-cloud-docs/citrix-netscaler-vpx#2]
In the global-load-balancing-options.md document there is a sentence, "In the global load balancing configuration, you have multiple NetScaler appliances in different data centers..."

Does this mean that each data center has multiple NetScaler appliances? Or that each data center has one, but there are multiple data centers involved?

My interpretation is that "In the global load balancing configuration, you have a single NetScaler appliance in multiple data centers..." However, I'm not sure if this is correct.

If possible, please clear up the phrasing to ensure we set up GSLB correctly.

Thanks!

**Comment by jbmitch** [comment]
@rbraddes  I updated the topic in question to give a little more clarity. Let me know what you think.
